"""add RepoAnalysis

Revision ID: 53382cced1cc
Revises: 788f653f2c18
Create Date: 2026-08-15 21:54:45.319783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53382cced1cc'
down_revision: Union[str, None] = '788f653f2c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('ai_summary', sa.JSON(), nullable=True),
    sa.Column('score', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_analyses_id'), 'repo_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_repo_analyses_repo_id'), 'repo_analyses', ['repo_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repo_analyses_repo_id'), table_name='repo_analyses')
    op.drop_index(op.f('ix_repo_analyses_id'), table_name='repo_analyses')
    op.drop_table('repo_analyses')
    # ### end Alembic commands ###
