"""add architecture_graph to RepoAnalysis

Revision ID: aba22d2be093
Revises: 53382cced1cc
Create Date: 2026-08-19 19:06:54.528305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aba22d2be093'
down_revision: Union[str, None] = '53382cced1cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo_analyses', sa.Column('architecture_graph', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo_analyses', 'architecture_graph')
    # ### end Alembic commands ###
