"""add performance_profile to RepoAnalysis

Revision ID: f1fb3d9b17c6
Revises: aba22d2be093
Create Date: 2026-08-19 20:38:43.485226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1fb3d9b17c6'
down_revision: Union[str, None] = 'aba22d2be093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo_analyses', sa.Column('performance_profile', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo_analyses', 'performance_profile')
    # ### end Alembic commands ###
